# Generated by Django 4.2.11 on 2024-03-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('fat_mass', models.FloatField(blank=True)),
                ('bone_mass', models.FloatField(blank=True)),
                ('muscle_mass', models.FloatField(blank=True)),
                ('hydration', models.FloatField(blank=True)),
            ],
        ),
    ]
