# Generated by Django 4.2.11 on 2024-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodycomposition',
            name='bone_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodycomposition',
            name='fat_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodycomposition',
            name='hydration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodycomposition',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
